export const INDUSTRIES = [
  "Technology",
  "Fintech",
  "Retail",
  "E-commerce",
  "Healthcare",
  "Education",
  "Real Estate",
  "Manufacturing",
  "Transportation",
  "Hospitality",
  "Entertainment",
  "Agriculture",
  "Construction",
  "Marketing",
  "Consulting",
  "Non-Profit",
  "Energy",
  "Telecommunications",
  "Food & Beverage",
  "Fashion",
];
